#!/usr/bin/env python3

import os
import sys

print("Content-Type: text/html")
print()
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("<title>CGI Test - Python</title>")
print("<style>")
print("body { font-family: Arial, sans-serif; margin: 20px; }")
print("h1 { color: #333; }")
print(".env-var { background: #f5f5f5; padding: 10px; margin: 5px 0; border-radius: 3px; }")
print("</style>")
print("</head>")
print("<body>")
print("<h1>CGI Test - Python Script</h1>")
print("<p>This page is generated by a Python CGI script.</p>")

print("<h2>Environment Variables:</h2>")
env_vars = [
    "REQUEST_METHOD", "QUERY_STRING", "CONTENT_LENGTH", "CONTENT_TYPE",
    "SERVER_NAME", "SERVER_PORT", "SCRIPT_NAME", "PATH_INFO",
    "REMOTE_ADDR", "HTTP_USER_AGENT", "HTTP_HOST"
]

for var in env_vars:
    value = os.environ.get(var, "Not set")
    print(f'<div class="env-var"><strong>{var}:</strong> {value}</div>')

print("<h2>Query String Parameters:</h2>")
query_string = os.environ.get("QUERY_STRING", "")
if query_string:
    params = query_string.split("&")
    for param in params:
        if "=" in param:
            key, value = param.split("=", 1)
            print(f'<div class="env-var"><strong>{key}:</strong> {value}</div>')
else:
    print("<p>No query string parameters.</p>")

print("<p><a href='/'>Back to Home</a></p>")
print("</body>")
print("</html>") 